/* ============================================
   SHARED PAGE STYLES
   Hypebeast-Luxe Design System (theme-aware)
   ============================================ */

const darkPageStyles = {
  /* ── Page Container ── */
  pageContainer: {
    background: 'var(--bg-primary)',
    minHeight: '100vh',
    color: 'var(--text-primary)',
  },

  /* ── Hero Section ── */
  hero: {
    background: 'linear-gradient(135deg, var(--glass-bg-hover) 0%, var(--bg-primary) 100%)',
    position: 'relative',
    overflow: 'hidden',
    padding: '80px 20px',
    textAlign: 'center',
  },
  heroPattern: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'var(--gradient-glow)',
    pointerEvents: 'none',
  },
  heroContent: {
    position: 'relative',
    zIndex: 1,
    maxWidth: '800px',
    margin: '0 auto',
  },
  heroTitle: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 'clamp(2.2rem, 5vw, 3.5rem)',
    fontWeight: 400,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--text-primary)',
    marginBottom: '16px',
  },
  heroSubtitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: 'clamp(0.95rem, 2vw, 1.15rem)',
    color: 'var(--text-secondary)',
    lineHeight: 1.7,
  },
  heroDecoration: {
    position: 'absolute',
    bottom: '-2px',
    left: 0,
    right: 0,
    height: '40px',
    background: 'var(--bg-primary)',
    clipPath: 'polygon(0 50%, 100% 0, 100% 100%, 0 100%)',
  },

  /* ── Page Content Wrapper ── */
  pageContent: {
    maxWidth: '1100px',
    margin: '0 auto',
    padding: '48px 20px',
  },

  /* ── Content Section Card ── */
  contentSection: {
    background: 'var(--bg-card)',
    border: '1px solid var(--glass-border)',
    borderRadius: '16px',
    padding: '40px',
    marginBottom: '28px',
    transition: 'border-color 0.3s ease',
  },

  /* ── Section Badge ── */
  sectionBadge: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, var(--white), #f0f0f0)',
    color: 'var(--black)',
    padding: '6px 16px',
    borderRadius: '9999px',
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '10px',
    fontWeight: 400,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    marginBottom: '18px',
  },
  valueBadge: {
    background: 'var(--glass-border-hover)',
    color: 'var(--text-primary)',
  },

  /* ── Section Title ── */
  sectionTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 'clamp(1.5rem, 3vw, 2rem)',
    color: 'var(--text-primary)',
    marginBottom: '24px',
    fontWeight: 700,
    fontStyle: 'italic',
  },

  /* ── Story / Paragraph ── */
  storyContent: {
    marginTop: '16px',
  },
  paragraph: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '14px',
    lineHeight: 1.8,
    color: 'var(--text-secondary)',
    marginBottom: '16px',
  },
  dropCap: {
    fontSize: '3.2rem',
    fontWeight: 700,
    float: 'left',
    lineHeight: 1,
    marginRight: '10px',
    background: 'linear-gradient(135deg, var(--text-primary), var(--text-secondary))',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },

  /* ── Values Section (accent bg) ── */
  valuesSection: {
    background: 'linear-gradient(135deg, var(--glass-bg-hover) 0%, var(--bg-card) 100%)',
    borderColor: 'var(--border-light)',
  },
  valuesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '20px',
    marginTop: '32px',
  },
  valueCard: {
    background: 'var(--glass-bg)',
    backdropFilter: 'blur(10px)',
    border: '1px solid var(--glass-border)',
    borderRadius: '12px',
    padding: '28px',
    textAlign: 'center',
    transition: 'all 0.3s ease',
    cursor: 'default',
  },
  valueIcon: {
    fontSize: '2.4rem',
    marginBottom: '16px',
  },
  valueTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '1.1rem',
    marginBottom: '12px',
    color: 'var(--text-primary)',
    fontWeight: 600,
  },
  valueDesc: {
    color: 'var(--text-muted)',
    lineHeight: 1.6,
    fontSize: '0.85rem',
    margin: 0,
  },

  /* ── Feature List ── */
  featureList: {
    listStyle: 'none',
    padding: 0,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '14px',
    marginTop: '24px',
  },
  featureItem: {
    background: 'var(--bg-primary)',
    padding: '18px 22px',
    borderRadius: '10px',
    border: '1px solid var(--glass-border)',
    borderLeft: '3px solid var(--text-primary)',
    fontSize: '14px',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    transition: 'all 0.3s ease',
  },
  featureCheck: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    background: 'linear-gradient(135deg, var(--white), #f0f0f0)',
    color: 'var(--black)',
    borderRadius: '50%',
    fontWeight: 'bold',
    flexShrink: 0,
    fontSize: '0.8rem',
  },

  /* ── Stats Grid ── */
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: '16px',
    marginTop: '28px',
  },
  statCard: {
    background: 'var(--glass-bg)',
    border: '1px solid var(--glass-border)',
    borderRadius: '12px',
    padding: '24px',
    textAlign: 'center',
    transition: 'all 0.3s ease',
  },
  statNumber: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '2rem',
    background: 'linear-gradient(135deg, var(--text-primary), var(--text-secondary))',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    lineHeight: 1.2,
  },
  statLabel: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '11px',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    marginTop: '6px',
  },

  /* ── Steps / Timeline ── */
  stepsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '20px',
    marginTop: '28px',
  },
  stepCard: {
    background: 'var(--glass-bg)',
    border: '1px solid var(--glass-border)',
    borderRadius: '12px',
    padding: '28px 24px',
    textAlign: 'center',
    transition: 'all 0.3s ease',
    position: 'relative',
  },
  stepNumber: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '2rem',
    background: 'linear-gradient(135deg, var(--text-primary), var(--text-secondary))',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    marginBottom: '12px',
    display: 'block',
  },
  stepTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    marginBottom: '10px',
  },
  stepDesc: {
    fontSize: '0.85rem',
    color: 'var(--text-muted)',
    lineHeight: 1.6,
    margin: 0,
  },

  /* ── Form Elements ── */
  formGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    fontFamily: "'Outfit', sans-serif",
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    padding: '14px 16px',
    background: 'var(--bg-primary)',
    border: '1px solid var(--border-light)',
    borderRadius: '10px',
    color: 'var(--text-primary)',
    fontFamily: "'Outfit', sans-serif",
    fontSize: '14px',
    outline: 'none',
    transition: 'border-color 0.3s ease',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: '14px 16px',
    background: 'var(--bg-primary)',
    border: '1px solid var(--border-light)',
    borderRadius: '10px',
    color: 'var(--text-primary)',
    fontFamily: "'Outfit', sans-serif",
    fontSize: '14px',
    outline: 'none',
    minHeight: '140px',
    resize: 'vertical',
    transition: 'border-color 0.3s ease',
    boxSizing: 'border-box',
  },
  submitButton: {
    background: 'linear-gradient(135deg, var(--white), #f0f0f0)',
    color: 'var(--black)',
    border: 'none',
    padding: '16px 40px',
    borderRadius: '10px',
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '14px',
    fontWeight: 400,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    width: '100%',
  },

  /* ── CTA / Banner ── */
  ctaSection: {
    background: 'linear-gradient(135deg, rgba(var(--accent-gold-rgb),0.12) 0%, var(--bg-card) 100%)',
    border: '1px solid rgba(var(--accent-gold-rgb),0.2)',
    borderRadius: '16px',
    padding: '48px 40px',
    textAlign: 'center',
    marginBottom: '28px',
  },
  ctaTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 'clamp(1.4rem, 3vw, 1.8rem)',
    color: 'var(--text-primary)',
    marginBottom: '14px',
    fontWeight: 700,
    fontStyle: 'italic',
  },
  ctaDesc: {
    color: 'var(--text-muted)',
    fontSize: '14px',
    lineHeight: 1.7,
    marginBottom: '24px',
    maxWidth: '600px',
    margin: '0 auto 24px',
  },
  ctaButton: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, var(--white), #f0f0f0)',
    color: 'var(--black)',
    padding: '14px 36px',
    borderRadius: '9999px',
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '13px',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    textDecoration: 'none',
    cursor: 'pointer',
    border: 'none',
    transition: 'all 0.3s ease',
  },

  /* ── Info Grid (contact, etc.) ── */
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
    marginTop: '24px',
  },
  infoCard: {
    background: 'var(--glass-bg)',
    border: '1px solid var(--glass-border)',
    borderRadius: '12px',
    padding: '24px',
    textAlign: 'center',
    transition: 'all 0.3s ease',
  },
  infoIcon: {
    fontSize: '2rem',
    marginBottom: '12px',
  },
  infoTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '0.95rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    marginBottom: '8px',
  },
  infoText: {
    fontSize: '0.85rem',
    color: 'var(--text-muted)',
    lineHeight: 1.5,
    margin: 0,
  },

  /* ── Table styles ── */
  table: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: '0',
    marginTop: '20px',
  },
  th: {
    background: 'rgba(var(--accent-gold-rgb),0.1)',
    color: 'var(--text-primary)',
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '12px',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    padding: '14px 16px',
    textAlign: 'left',
    borderBottom: '1px solid var(--border-light)',
  },
  td: {
    padding: '14px 16px',
    fontSize: '13px',
    color: 'var(--text-secondary)',
    borderBottom: '1px solid var(--glass-border)',
    fontFamily: "'Outfit', sans-serif",
  },

  /* ── Accordion / FAQ ── */
  faqItem: {
    background: 'var(--bg-primary)',
    border: '1px solid var(--glass-border)',
    borderRadius: '10px',
    marginBottom: '10px',
    overflow: 'hidden',
  },
  faqQuestion: {
    padding: '18px 22px',
    fontSize: '14px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontFamily: "'Outfit', sans-serif",
  },
  faqAnswer: {
    padding: '0 22px 18px',
    fontSize: '13px',
    color: 'var(--text-muted)',
    lineHeight: 1.7,
    fontFamily: "'Outfit', sans-serif",
  },

  /* ── Job Card / Listing ── */
  jobCard: {
    background: 'var(--glass-bg)',
    border: '1px solid var(--glass-border)',
    borderRadius: '12px',
    padding: '28px',
    marginBottom: '14px',
    transition: 'all 0.3s ease',
  },
  jobTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '1.1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    marginBottom: '8px',
  },
  jobMeta: {
    fontSize: '0.8rem',
    color: 'var(--text-muted)',
    marginBottom: '12px',
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
  },
  jobDesc: {
    fontSize: '0.85rem',
    color: 'var(--text-secondary)',
    lineHeight: 1.6,
    margin: 0,
  },
  jobTag: {
    display: 'inline-block',
    background: 'rgba(var(--accent-gold-rgb),0.1)',
    color: 'var(--text-primary)',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },

  /* ── Legal Text ── */
  legalText: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '13px',
    lineHeight: 1.8,
    color: 'var(--text-secondary)',
    marginBottom: '14px',
  },
  legalHeading: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    marginTop: '28px',
    marginBottom: '12px',
  },
  legalList: {
    paddingLeft: '20px',
    margin: '12px 0',
  },
  legalListItem: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    lineHeight: 1.8,
    marginBottom: '6px',
  },

  /* ── Tier / Pricing Card ── */
  tierGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '20px',
    marginTop: '28px',
  },
  tierCard: {
    background: 'var(--glass-bg)',
    border: '1px solid var(--glass-border)',
    borderRadius: '16px',
    padding: '32px',
    textAlign: 'center',
    transition: 'all 0.3s ease',
    position: 'relative',
  },
  tierCardHighlighted: {
    background: 'rgba(var(--accent-gold-rgb),0.06)',
    border: '1px solid rgba(var(--accent-gold-rgb),0.25)',
  },
  tierTitle: {
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: '1.3rem',
    letterSpacing: '0.08em',
    color: 'var(--text-primary)',
    marginBottom: '8px',
  },
  tierPrice: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '2rem',
    fontWeight: 700,
    background: 'linear-gradient(135deg, var(--text-primary), var(--text-secondary))',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    marginBottom: '16px',
  },
  tierFeature: {
    fontSize: '0.85rem',
    color: 'var(--text-muted)',
    padding: '8px 0',
    borderBottom: '1px solid var(--glass-border)',
  },
};

export default darkPageStyles;
