// Chartered cities of the Philippines (alphabetical).
// Used by the Settings > Profile "Place" field as a searchable datalist.
const PH_CITIES = [
  "Alaminos", "Angeles", "Antipolo",
  "Bacolod", "Bacoor", "Bago", "Baguio", "Bais", "Balanga", "Batac", "Batangas City",
  "Bayawan", "Baybay", "Bayugan", "Biñan", "Bislig", "Bogo", "Borongan", "Butuan",
  "Cabadbaran", "Cabanatuan", "Cabuyao", "Cadiz", "Cagayan de Oro", "Calamba",
  "Calapan", "Calbayog", "Caloocan", "Candon", "Canlaon", "Carcar", "Catbalogan",
  "Cauayan", "Cavite City", "Cebu City", "Cotabato City",
  "Dagupan", "Danao", "Dapitan", "Dasmariñas", "Davao City", "Digos", "Dipolog",
  "Dumaguete",
  "El Salvador", "Escalante",
  "Gapan", "General Santos", "General Trias", "Gingoog", "Guihulngan",
  "Himamaylan",
  "Iligan", "Iloilo City", "Imus", "Iriga", "Isabela City", "Ilagan",
  "Kabankalan", "Kidapawan", "Koronadal",
  "La Carlota", "Lamitan", "Laoag", "Lapu-Lapu", "Las Piñas", "Legazpi",
  "Ligao", "Lipa", "Lucena",
  "Maasin", "Mabalacat", "Makati", "Malabon", "Malaybalay", "Malolos", "Mandaluyong",
  "Mandaue", "Manila", "Marawi", "Marikina", "Masbate City", "Mati", "Meycauayan",
  "Muntinlupa", "Muñoz",
  "Naga (Camarines Sur)", "Naga (Cebu)", "Navotas",
  "Olongapo", "Ormoc", "Oroquieta", "Ozamiz",
  "Pagadian", "Palayan", "Panabo", "Parañaque", "Pasay", "Pasig", "Passi", "Puerto Princesa",
  "Quezon City",
  "Roxas City",
  "Sagay", "Samal", "San Carlos (Negros)", "San Carlos (Pangasinan)", "San Fernando (La Union)",
  "San Fernando (Pampanga)", "San Jose (Nueva Ecija)", "San Jose del Monte", "San Juan",
  "San Pablo", "San Pedro", "Santa Rosa", "Santiago", "Silay", "Sipalay", "Sorsogon City",
  "Surigao City",
  "Tabaco", "Tabuk", "Tacloban", "Tacurong", "Tagaytay", "Tagbilaran", "Taguig",
  "Tagum", "Talisay (Cebu)", "Talisay (Negros Occidental)", "Tanauan", "Tandag",
  "Tangub", "Tanjay", "Tarlac City", "Tayabas", "Toledo", "Trece Martires", "Tuguegarao",
  "Urdaneta",
  "Valencia", "Valenzuela", "Victorias", "Vigan",
  "Zamboanga City",
];

export default PH_CITIES;
